Repository Rookout/docs, pull requests merged in 2022-03, with the labels that each got.

#515 RK-11647 Updated follow-redirect
  website/yarn.lock
Labels: DeployEnforcer/MergeOnceApproved

#516 RK-11712 - use service account in order to keep the session alive
  .circleci/config.yml
  website/package.json
Labels: docs, Documentation

#518 RK-11714 - fix GOOGLE_APPLICATION_CREDENTIALS export command
  website/package.json
Labels: DeployEnforcer/MergeOnceApproved, docs, Documentation

#519 RK-11725 - Docs circleci
  .circleci/config.yml
  website/package.json
Labels: DeployEnforcer/MergeOnceApproved, docs, Documentation

#520 RK-11726 - Docs circleci
  .circleci/config.yml
Labels: DeployEnforcer/MergeOnceApproved, docs, Documentation

#521 RK-11727 - Docs circleci
  .circleci/config.yml
Labels: DeployEnforcer/MergeOnceApproved, docs, Documentation

#523 RK-11733 - Docs circleci
  .circleci/config.yml
  website/package.json
Labels: DeployEnforcer/MergeOnceApproved, docs, Documentation

#525 RK-11739 - fix deploy path and env var
  .circleci/config.yml
Labels: DeployEnforcer/MergeOnceApproved

#526 RK-11742 - attach workspace for local gcp json
  .circleci/config.yml
Labels: DeployEnforcer/MergeOnceApproved

#531 RK-11752 - Docs circleci
  .circleci/config.yml
Labels: DeployEnforcer/MergeOnceApproved, docs, Documentation

#532 RK-11755 - Docs circleci
  .circleci/config.yml
Labels: DeployEnforcer/MergeOnceApproved, docs, Documentation

#535 RK-11863 - Webpack mangling
  docs/etl-controller-config.md
  docs/node-setup.md
Labels: DeployEnforcer/MergeOnceApproved

#489 RK-10976 - Datastore docs and Controller docs improvements
  docs/collaboration.md
  docs/dop-config.md
  docs/dop-install.md
  docs/dop-intro.md
  docs/etl-controller-config.md
  docs/etl-controller-docker.md
  docs/etl-controller-install.md
  docs/etl-controller-intro.md
  docs/etl-controller-k8s.md
  docs/license.md
  website/core/Footer.js
  website/sidebars.json
  website/static/css/custom.css
  website/static/img/screenshots/data_processed.png
  website/static/img/screenshots/datastore_diagram.png
Labels: DeployEnforcer/MergeOnceApproved

#537 RK-11877 - up-node 12.22.11, 14.19.1, 16.14.2
  docs/node-setup.md
Labels: DeployEnforcer/MergeOnceApproved
